# You can use this file to create a conda environment for this pipeline:
#   conda create env create -f environment.yml
name: nfcore-module-nanoplot
channels:
  - conda-forge
  - bioconda
  - defaults
  - plotly
dependencies:
  ## bioconda packages
  - nanoplot=1.30.1
  - psutil=5.7.0
  - plotly-orca=1.3.1
  - requests=2.24.0
