# You can use this file to create a conda environment for the samtools module:
#   conda env create -f environment.yml
name: nfcore-samtools-0.1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## basic packages and dependencies
  - pigz=2.3.4

  ## bioconda packages, see above
  - samtools=1.9