name: docker-build-push

on:
  push:
    branches: [ master ]

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            module-name: ['bedtools','cutadapt','fastqc','get_crosslinks','get_crosslinks_coverage','icount','paraclu','peka','samtools','star','umi_tools','seqtk','bowtie2']
    steps:
      - uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: luslab/nf-modules-${{matrix.module-name}}
          path: tools/${{matrix.module-name}}
          tags: latest