name: module-testing

on:
  #push:
  #  branches: [ feat-chris ]
  pull_request:
    branches: [ master ]

jobs:
  test-modules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['20.07.1','']
        tag: ['base']
        docker-name: ['Dockerfile']
        module-name: ['htseq', 'velocyto', 'flye', 'homer', 'umi_tools', 'fastqc', 'cutadapt', 'bedtools', 'samtools', 'get_crosslinks','get_crosslinks_coverage', 'icount', 'minimap2', 'seqtk', 'paraclu', 'luslab_genome_tools', 'luslab_linux_tools', 'bowtie2', 'metadata', 'minionqc', 'tantan', 'hisat2', 'star', 'multiqc', 'macs2', 'racon', 'seacr', 'nanoplot', 'busco', 'last', 'blast', 'infernal', 'hmmer', 'cdhit', 'mafft', 'phyml', 'emboss', 'augustus', 'deeptools', 'purge_haplotigs', 'purge_dups', 'porechop', 'pilon', 'repeatmodeler', 'filtlong']
        include:
          - nxf_ver: '20.07.1'
            tag: 'cpu'
            docker-name: 'Dockerfile.cpu'
            module-name: 'guppy'
          - nxf_ver: ''
            tag: 'cpu'
            docker-name: 'Dockerfile.cpu'
            module-name: 'guppy'
    steps:
      - uses: actions/checkout@v2
      - name: Set version and tags
        id: ver
        run: |
          VERSION="0.0.0"
          test -f tools/${{matrix.module-name}}/${{matrix.docker-name}} && export DOCKER_EXISTS=true || echo "Dockerfile does not exist, skipping step"
          if [ -v DOCKER_EXISTS ]; then VERSION=`cat tools/${{matrix.module-name}}/VERSION` && echo "::set-output name=version::$(echo $VERSION)"; fi
          if [ $? -ne 0 ]; then exit 1; fi
          echo "version: $VERSION"
        shell: bash
      - name: Install Nextflow
        run: |
          export NXF_VER=${{matrix.nxf_ver}}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Docker build
        run: |
           test -f tools/${{matrix.module-name}}/${{matrix.docker-name}} && export DOCKER_EXISTS=true || echo "Dockerfile does not exist, skipping step"
           if [ -v DOCKER_EXISTS ]; then docker build -f tools/${{matrix.module-name}}/${{matrix.docker-name}} -t luslab/nf-modules-${{matrix.module-name}}:latest -t luslab/nf-modules-${{matrix.module-name}}:${{matrix.tag}}-${{steps.ver.outputs.version}} tools/${{matrix.module-name}}; fi
      - name: Module testing
        run: |
          nextflow -C ${GITHUB_WORKSPACE}/tools/${{matrix.module-name}}/test/nextflow.config run ${GITHUB_WORKSPACE}/tools/${{matrix.module-name}}/test/main.nf
